# Generated by Django 2.1.7 on 2019-02-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cotacao', models.DateTimeField(verbose_name='data cotacao')),
            ],
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cotacao',
            name='moeda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.Moeda'),
        ),
    ]
