# Generated by Django 2.1.7 on 2019-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='valor_cotacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
