# Generated by Django 2.1.7 on 2019-02-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0002_cotacao_valor_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='data_cotacao',
            field=models.CharField(max_length=200),
        ),
    ]
